### ISSUE TITLE
Enquiry about the installation issue

### ISSUE THREAD

**Issue by chang111** [TradeMaster-NTU/TradeMaster#10]
Hi developers,

When I try to run the command: "pip install git+https://github.com/TradeMaster-NTU/TradeMaster.git"

I met the issue: 
ERROR: git+https://github.com/TradeMaster-NTU/TradeMaster.git does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.

**Comment by ai-gamer** [comment]
Sorry. We have revised the installation command. Please use: git clone https://github.com/TradeMaster-NTU/TradeMaster.git instead of the previous one.

**Comment by chang111** [comment]
Noted with thanks. With the installation going, I found the "onnxruntime-gpu" is not supported by MacBook. I try to install by "pip install onnxruntime". Did work for the framework?
