### ISSUE TITLE
no cuda issue while installation issue

### ISSUE THREAD

**Issue by sweetconda** [TradeMaster-NTU/TradeMaster#111]
Hi developers,

My server:  region-42.seetacloud.com 
SSH Port: 33754
root
5ikP1F1Tj6

When I try to run the command: "python tools/algorithmic_trading/train.py"

I met the issue:
ERROR: No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'

But I followed the instructions step by step to install it.

Would you please help see what the problem is? Thank you!
The server information is as above.  Thanks.

**Comment by sunshuo01** [comment]
@sweetconda , May I ask your operating system? Is there GPU available on your server?

**Comment by sweetconda** [comment]
Yes, It's RTX 2080 Ti(11GB),  CPU is 12 vCPU Intel(R) Xeon(R) Platinum 8255C CPU @ 2.50GHz.

**Comment by sunshuo01** [comment]
It seems you have not installed cuda toolkits. TradeMaster requires cuda 11.3+ to run. You can try to download cuda at this link https://developer.nvidia.com/cuda-11.3.0-download-archive

**Comment by sweetconda** [comment]
Thanks. I installed cuda toolkits using the following command, is this okay? 
conda install pytorch==1.12.1 torchvision==0.13.1 torchaudio==0.12.1 cudatoolkit=11.3 -c pytorch

**Comment by sunshuo01** [comment]
No. It is not enough. Please follow the link above and select your corresponding operating system and versions. Then, there will be the corresponding commands. Take Ubuntu 20.04 as an example:
wget https://developer.download.nvidia.com/compute/cuda/11.3.0/local_installers/cuda_11.3.0_465.19.01_linux.run
sudo sh cuda_11.3.0_465.19.01_linux.run

**Comment by sweetconda** [comment]
Thank you. I'll try again.
