### ISSUE TITLE
 No such file or directory:adam_mse/checkpoints/best.pth

### ISSUE THREAD

**Issue by sweetconda** [TradeMaster-NTU/TradeMaster#112]
Hi, When I installed, run  "python tools/algorithmic_trading/train.py" , then error msg is: 

FileNotFoundError: [Errno 2] No such file or directory: '/root/TradeMaster/work_dir/algorithmic_trading_FX_deepscalper_deepscalper_adam_mse/checkpoints/best.pth'.

Would you please tell me how to solve this problem? thanks.

**Comment by DVampire** [comment]
Sorry, the line 30 of tools/algorithmic_trading/train.py should be set "task_name" to "train"
`parser.add_argument("--task_name", type=str, default="test")`
to
`parser.add_argument("--task_name", type=str, default="train")`

**Comment by sweetconda** [comment]
It's runing :)    Thank you!

BTW, CPU usage: 100%, GPU usage: 12%,  is it normal?

----------------------
output msgs:
...
...
Valid Episode: [20/20]
+--------------+-------------+------------+--------------+
| Total Return | Sharp Ratio | Volatility | Max Drawdown |
+--------------+-------------+------------+--------------+
|  -0.147375%  |  -53.236436 | 0.000090%  |  0.147375%   |
+--------------+-------------+------------+--------------+
train end

**Comment by sunshuo01** [comment]
The 12% GPU usage is fine for reinforcement learning. I recommend to check the tutorials we provided with more details on the usage of the platform. BTW, could you please kindly Starred and Fork TradeMaster on Github :blush:? Your support matters a lot for us.

**Comment by sweetconda** [comment]
Glad to receive your suggestions, already starred and forked TradeMaster. Your work is amazing, thank you.
