### ISSUE TITLE
difference between save_model and save_best_model

### ISSUE THREAD

**Issue by JeffQuantFin** [TradeMaster-NTU/TradeMaster#114]
在 train_and_valid 中
1)每次valid 时 调用 save_model
2)当整个train_and_valid 结束时，会调用 save_best_model   

save_best_model 保存的是 【训练结束时的 模型】，还是 epoch = np.argmax(valid_score_list)  时【 表现最佳的模型】？

从代码看，属于保存 训练结束时的 模型?   并不是保存的 【表现最佳的模型】？

**Comment by DVampire** [comment]
Sorry, it was an oversight on our part and I have fixed it. Thank you for your attention.
