### ISSUE TITLE
Documents for the difference of RL environments 

### ISSUE THREAD

**Issue by JeffQuantFin** [TradeMaster-NTU/TradeMaster#115]
是否有以下环境的 一些介绍资料？比如porfolio 各个环境的 区别？
一、Porfolio
1) deeptrader_environment
2)eiie_environment
3)environment
4)investtor_imitator_environment
5)sarl_environment
二、high_frequency_trading
6) environment
三、order_excution
7) eteo_environment.py
8) pd_environment.py

**Comment by sunshuo01** [comment]
Hi, Jeff

Thanks for your interest on the project :blush:. We are working on documents of TradeMaster. It will hopefully be public available in a few weeks. BTW, could you please open issues with English if possible so that everyone can understand and learn from our discussions?

**Comment by JeffQuantFin** [comment]
sure. in English
