### ISSUE TITLE
bug cannot run tools/train_eiie.py

### ISSUE THREAD

**Issue by JeffQuantFin** [TradeMaster-NTU/TradeMaster#116]
![bug1_trader_master](https://user-images.githubusercontent.com/34833991/226182237-c6e6c740-6859-4801-b63b-34f9cd347448.png)

**Comment by DVampire** [comment]
It looks like you are using pytest to start train_eiie.py. I have changed "test_deeptrader" to "main", which should avoid using pytest by default. I hope this helps you.
