### ISSUE TITLE
what is the definition of "buys" and "sells" in the dataset for eteo environment? 

### ISSUE THREAD

**Issue by JeffQuantFin** [TradeMaster-NTU/TradeMaster#126]
whis is the definition of the dataset of eteo  ？
1、midpoint
2、buys
3、sells
4、bids_distance_0
5、bids_notaional_0
6、bids_cancel_notional_0
7、bids_limit_notional_0
8、bids_market_notional_0

I can guess some,not very sure

**Comment by qinmoelei** [comment]
Hi

The midpoint denotes (ask0_price+bid0_price)/2, where ask0_price is the lowest unit price that a seller want to sell and bid0_price is the highest unit price that a buyer want to buy.

The buy and sell indicates the value of the executed order between 2 data points

The bids_distance_0 indicates (ask0_price-midpoint )/midpoint 

The bids_notaional_0 indicates the current bid0_price's size, where you can find bids_notaional_0=bids_limit_notional_0+bids_market_notional_0-bids_cancel_notional_0, indicating the 3 sources of the size: market maker, limit order and those are cancelled.

**Comment by qinmoelei** [comment]
Hi

The midpoint denotes (ask0_price+bid0_price)/2, where ask0_price is the lowest unit price that a seller want to sell and bid0_price is the highest unit price that a buyer want to buy.

The buy and sell indicates the value of the executed order between 2 data points

The bids_distance_0 indicates (ask0_price-midpoint )/midpoint 

The bids_notaional_0 indicates the current bid0_price's size, where you can find bids_notaional_0=bids_limit_notional_0+bids_market_notional_0-bids_cancel_notional_0, indicating the 3 sources of the size: market maker, limit order and those are cancelled.

Hope this can help, let me know if you have further questions.
