### ISSUE TITLE
Enquiry about the jupyter memory problem

### ISSUE THREAD

**Issue by chang111** [TradeMaster-NTU/TradeMaster#14]
HI Teams,

When I tried to run the "DeepScalper" tutorial, I met the below issue:

"your server is down"

I think it is because the mac can support the memory used by jupyter. Could you help find another solution. 

Many thanks!

**Comment by qinmoelei** [comment]
Dear sir:
Thanks for your feedback. While we are looking for the solution for the jupyter notebook for mac, you can alternatively use the code from the file  `experiment\AT\DeepScalper\experiment.py` after you have followed the installation instruction if you want to try the DeepScalper algorithms. This code do not contains the downloading data processure but by default setting, there has already been a dataset there.
Please let me know if this works for you.
Best regards

**Comment by ai-gamer** [comment]
Dear chang111,

The memory issue might be caused due to memory limit of jupyter notebook on Mac. We can alternatively run the code at `experiment\AT\DeepScalper\experiment.py` with some Python IDE (e.g., Pycharm). I hope this helps.
