### ISSUE TITLE
How to train the LSTM in the SARL?

### ISSUE THREAD

**Issue by Tint0ri** [TradeMaster-NTU/TradeMaster#141]
I noticed  sarl_environment.py use pretrained parameters from LSTM.pth. Just wonder how to train the LSTM model and get the LSTM.pth by myself.

**Comment by qinmoelei** [comment]
You may refer https://github.com/TradeMaster-NTU/TradeMaster/tree/main/agent/SARL/encoder for details.
The basic process is a supervised learning where the X indicates technical indicators along a fixed length of dates and the Y is 0 or 1 indicates whether in the future, the price will go up or go down and we use a LSTM network to fit it.
