### ISSUE TITLE
ROOT path not working with pyenv and interactive shell

### ISSUE THREAD

**Issue by HadiSDev** [TradeMaster-NTU/TradeMaster#142]
Hi. I tried setting up one of the tutorials but got an annoying error with the ROOT path because __file__ returns a path relative to the virtualenv. 

To make it work with all cases it we just have to change to:
```
import os
FILE_PATH = os.path.dirname(os.path.abspath("__file__"))
ROOT = str(Path(FILE_PATH).resolve().parents[3])
```

example for **AlgorithmicTradingDataset**

**Comment by DVampire** [comment]
Thanks for your attention, we will solve the relative path problem caused by `pip install trademaster`

**Comment by HadiSDev** [comment]
@DVampire if you need an extra hand I can assist you with a PR ?

**Comment by DVampire** [comment]
sure, if you have time, you can submit a PR and welcome to participate in our project
