### ISSUE TITLE
Is the algorithmic_trading using DDQN or DQN? 

### ISSUE THREAD

**Issue by aslamy** [TradeMaster-NTU/TradeMaster#143]
Hi

Is the algorithmic_trading using DDQN or DQN? If not, is it possible to convert it to DDQN?

**Comment by DVampire** [comment]
It is DQN, if you want to use DDQN, you need to implement the corresponding agent in `trademaster/agents/algorithmic_trading` by following the example of dqn. I think the cost of transfer is relatively low, if you have any questions you can always contact me.

**Comment by aslamy** [comment]
Hi
Thank you for your response! Do you mean if I follow TradeMaster/agents/high_frequency_trading? I only found DDQN for high_frequency_trading.  For now, I understand algorithmic_trading very well. I need to sit down and comprehend high_frequency_trading.

**Comment by DVampire** [comment]
Yes, our high_frequency_trading is DDQN, you can refer to it `https://github.com/TradeMaster-NTU/TradeMaster/blob/1.0.0/trademaster/agents/high_frequency_trading/ddqn.py`
