### ISSUE TITLE
What does it mean when hold_volume is negative?

### ISSUE THREAD

**Issue by ysyyork** [TradeMaster-NTU/TradeMaster#144]
Hi, i'm trying to figure out the code logic for AlgorithmicTradingEnvironment. 

I don't quite understand the below [line](https://github.com/TradeMaster-NTU/TradeMaster/blob/1d646cc3c85953e93432898c5a650dff3e5ef2ff/trademaster/environments/algorithmic_trading/environment.py#L172) as when I'm running Tutorial2_DeepScalper.ipynb, i can see negative hold_volume. Could someone help explain what does it stands for?

**Comment by qinmoelei** [comment]
It means that you are shorting this asset. Particularly, if the holding_volume is -1, then you borrow a BTC from a market maker and sell it right away. Now you have the cash sold for the BTC yet owe the market maker a BTC.

**Comment by ysyyork** [comment]
> It means that you are shorting this asset. Particularly, if the holding_volume is -1, then you borrow a BTC from a market maker and sell it right away. Now you have the cash sold for the BTC yet owe the market maker a BTC.

Got it, thanks for you reply! didn't know this support shorting
