### ISSUE TITLE
Error running Tutorial3_SARL.ipynb ray.get(f.remote(sharpe['table'])) KeyError: 'table'

### ISSUE THREAD

**Issue by joshwigginton** [TradeMaster-NTU/TradeMaster#147]
When running Tutorial3_SARL.ipynb, I am getting error when running trainer.test(). 

KeyError                                  Traceback (most recent call last)
Cell In[6], line 12
     10 ray.init(ignore_reinit_error=True)
     11 register_env("portfolio_management_sarl", lambda config: env_creator("portfolio_management_sarl")(config))
---> 12 trainer.test();

File /home/TradeMaster/trademaster/trainers/portfolio_management/sarl_trainer.py:167, in PortfolioManagementSARLTrainer.test(self)
    164         # ray.get(f.remote("Test Best Episode Reward Sum: {:04f}".format(episode_reward_sum))
    165         break
--> 167 ray.get(f.remote(sharpe['table']))
    168 rewards = self.test_environment.save_asset_memory()
    169 assets = rewards["total assets"].values

KeyError: 'table'

I was able to comment out line #167 to get the code to complete.

**Comment by XiaHaochong98** [comment]
Thank you for your feedback, we have fixed this problem in the latest update.
