### ISSUE TITLE
Error installing packages in colab 

### ISSUE THREAD

**Issue by hom-bahrani** [TradeMaster-NTU/TradeMaster#155]
Hi many thanks for this wonderful resource, I have a question if I may. I tried to install the packages in your new [colab version](https://colab.research.google.com/drive/10M3F6qF8qJ31eQkBR7B6OHhYCR1ZUlrp#scrollTo=4TKpEroeFdT4) but there seems to be many conda packages in the `requirements.txt` and I get this type of error:

```
ERROR: Could not find a version that satisfies the requirement ca-certificates (from versions: none)
ERROR: No matching distribution found for ca-certificates
```

How did you manage to install the all the dependencies? 

One workaround I tried is to install conda in colab by running this cell

```
!pip install -q condacolab
import condacolab
condacolab.install()
```
then converting the `requirements.txt` into this [environment.yaml](https://github.com/hom-bahrani/TradeMaster/blob/1.0.0/environment.yaml) file but the installation process is very slow (over 1 hour) as there are many dependencies. Ideally I would like to install with pip and was wondering if you have a solution?

**Comment by ZONG0004** [comment]
We are very sorry that the requirement file was mistakenly modified during one update and we have uploaded the correct one. Please try the latest colab version.
