### ISSUE TITLE
"pip install -r requirements.txt" error

### ISSUE THREAD

**Issue by ztwe** [TradeMaster-NTU/TradeMaster#159]
Collecting gym<0.22 (from ray[rllib]==1.13.0->-r requirements.txt (line 20))
  Using cached gym-0.21.0.tar.gz (1.5 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      error in gym setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

**Comment by DVampire** [comment]
Sorry, an update uploaded the wrong requirements.txt, we have fixed this problem, please pull the new requirements.txt again. if you encounter new problems, please feel free to contact me.

**Comment by ztwe** [comment]
I pulled the requirements.txt yesterday. So the file should be the newest.

**Comment by XiaHaochong98** [comment]
Hi ztwe, did you start from a new environment and installed requirements.txt according to the [instructions](https://github.com/TradeMaster-NTU/TradeMaster/blob/1.0.0/installation/requirements.md)?

**Comment by ztwe** [comment]
No, I used the old environment which had installed the wrong requirements.txt (over 100+ library).

**Comment by XiaHaochong98** [comment]
Sorry for the confusion, please start from a new environment and reinstall all the things.

**Comment by ztwe** [comment]
The new environment still reports the error.

When I change the gym version to 0.26.2, it report the following error:
ERROR: Cannot install gym==0.26.2 and ray[rllib]==1.13.0 because these package versions have conflicting dependencies.

**Comment by DVampire** [comment]
maybe you can try `pip install gym==0.21.0 gymnasium==0.27.1`

**Comment by DVampire** [comment]
We recommend using the following environment installation process https://github.com/TradeMaster-NTU/TradeMaster/blob/1.0.0/installation/requirements.md

**Comment by ztwe** [comment]
I change the version of setuptools, then the problem is solved.
pip install --upgrade pip setuptools==57.5.0

**Comment by VashStan** [comment]
pip install --upgrade pip setuptools==62.3.0

I use this version，and it works
