### ISSUE TITLE
"python tools/algorithmic_trading/train.py" error

### ISSUE THREAD

**Issue by ztwe** [TradeMaster-NTU/TradeMaster#160]
labeling_util.py
ModuleNotFoundError: No module named 'dtaidistance'

ModuleNotFoundError: No module named 'fastdtw'

**Comment by ztwe** [comment]
Solve the problem through piping install dtaidistance and fastdtw.

**Comment by XiaHaochong98** [comment]
Thank you for pointing this out. The Toolbox is under development and the requirements haven't been updated in time. We have fixed this in the latest version.
