### ISSUE TITLE
Will the team releases more documents

### ISSUE THREAD

**Issue by ztwe** [TradeMaster-NTU/TradeMaster#161]
The project is complex and hard to fully understand. It is appreciate to release more documents.

**Comment by sunshuo01** [comment]
Hi, thanks for your interest on the project. We are preparing the soft document recently. A preliminary version is available at https://trademaster.readthedocs.io/en/latest/  We will release it when it is finished.

**Comment by ztwe** [comment]
Looking forward to it very much!
