### ISSUE TITLE
How can I retrain the sarl encoder?

### ISSUE THREAD

**Issue by Gikiman** [TradeMaster-NTU/TradeMaster#164]
I want to add some features to the SARL agent. However, since it will go through a pre-trained encoder whose dimension is fixed, I need to retrain the SARL encoder for the new features. Can you describe the training pipeline, or better yet, upload it to the repository?

**Comment by qinmoelei** [comment]
Hi,
You may refer to this [issue](https://github.com/TradeMaster-NTU/TradeMaster/issues/141)
More specifically, you can check the [code](https://github.com/TradeMaster-NTU/TradeMaster/tree/main/agent/SARL/encoder)
