### ISSUE TITLE
pretrained mode loading

### ISSUE THREAD

**Issue by stevexxs** [TradeMaster-NTU/TradeMaster#179]
Hi,

some model are loading pretrained model file with fixed input dimension. such as "sarl", "imitator model"
`
self.net.load_state_dict(self.network_dict)
`
how this pretrained mode is generated, and is there any manual to pretrain our own model ?

**Comment by qinmoelei** [comment]
Sorry for the late reply. 
You may refer the previous version of TradeMaster for how we build the model.
More specifically, for IMIT, here is the [link](https://github.com/TradeMaster-NTU/TradeMaster/tree/main/agent/Investor_Imitator/logic_discriptor).
For SARL, here is the [link](https://github.com/TradeMaster-NTU/TradeMaster/tree/main/agent/SARL/encoder)
Sorry for the troubles. The reason why we don't show the pretrain part is that this process is not owned by every algorithm and therefore is hard to cooperate with the current code framework where each algorithm is in a uniform code format.
