### ISSUE TITLE
Backtest

### ISSUE THREAD

**Issue by CoderM8n** [TradeMaster-NTU/TradeMaster#192]
I noticed for backtesting, the time period is not shown, it is just "times". How then do we benchmark algorithm return to the buy and hold benchmark?

**Comment by qinmoelei** [comment]
Since you have already gotten the original data, there is no need to go through the whole RL environment if your strategy is to buy and hold. A more efficient way would be to look into the dataset's first timestamp and last timestamp and calculate the return rate based on their price.

**Comment by CoderM8n** [comment]
got it thank you
