### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by CoderM8n** [TradeMaster-NTU/TradeMaster#193]
I notice that datasets are all in the cfg file? how then should user imported data be used?

**Comment by qinmoelei** [comment]
You should first determine what your data looks like and what kind of task you want. Then, based on this, you can register your task and dataset; see https://github.com/TradeMaster-NTU/TradeMaster/blob/1.0.0/trademaster/datasets/portfolio_management/dataset.py as an example of a dataset for portfolio management. Then the dataset will be used to construct the corresponding RL environment.  

If you want to import new data for a given task, then you can specify it in the config file by providing its path. Please notice that the data structure should be the same as the given example.

**Comment by CoderM8n** [comment]
Excellent thank you!
