### ISSUE TITLE
RL Agent

### ISSUE THREAD

**Issue by CoderM8n** [TradeMaster-NTU/TradeMaster#194]
i notice that there is no function to call the RL Agent, it seems like the RL agent is selected and built into the CFG?

**Comment by qinmoelei** [comment]
The algorithm is selected in the config file, see https://github.com/TradeMaster-NTU/TradeMaster/blob/1.0.0/configs/portfolio_management/portfolio_management_dj30_eiie_eiie_adam_mse.py as an example. The cfg is how the config in the py file is being transferred in the different modules in the trade master.
