### ISSUE TITLE
about pre trained model

### ISSUE THREAD

**Issue by RYUCK002** [TradeMaster-NTU/TradeMaster#204]
Hello 
I wonder how to customize the provided pre trained model  such as trademaster/pretrained/logic_discriptor/AR/best_model/discroptor_parameter.pth
trademaster/pretrained/logic_discriptor/SR/best_model/discroptor_parameter.pth
etc ...
 in my customized tests

thanks

**Comment by qinmoelei** [comment]
You may refer to [this issue ](https://github.com/TradeMaster-NTU/TradeMaster/issues/179)
