### ISSUE TITLE
Data Preprocess Source and Custom Dataset

### ISSUE THREAD

**Issue by cpzz50** [TradeMaster-NTU/TradeMaster#205]
This question is about BTC high frequency trading dataset provided.

From the csv file. Some columns like **[bid1_price]** has number **[23090.7]**,  but other columns like **[high]** have number **[-0.8507737401414914]**. Seems like some columns are normalized but others are not. Please advise how these data are preprocessed so I can put my own data into training.

Also about preprocessing, README indicate that the data is from Kaggle, which I found the original data doesn't contain indicators in the csv file. Wondering if it's possible disclose how those technical indicators are preprocessed.

Thank you

**Comment by qinmoelei** [comment]
[EarnHFT](https://github.com/qinmoelei/EarnHFT) contains a more detailed description of the [data preprocess](https://github.com/qinmoelei/EarnHFT/tree/main/data_preprocess), which members also develop from TradeMaster. For high-frequency trading for crypto, the two repos share the same setting, and [EarnHFT](https://github.com/qinmoelei/EarnHFT) is much easier to read.
