### ISSUE TITLE
Logging losses and reward with Tensorboard

### ISSUE THREAD

**Issue by DeepAnonymous** [TradeMaster-NTU/TradeMaster#59]
I have an issue with critic losses (increasing) when training AlphaMix+, please help to take a look at this issue.

https://github.com/ai-gamer/PRUDEX-Compass/issues/23

The same is applied for DeepTrader implementation in this repo (critic losses creasing). I wonder is there any issue with the code regarding critic losses, could you please have a check/comment on this.

Thank you.

**Comment by ai-gamer** [comment]
The critic loss value is usually not very informative as describe in https://stackoverflow.com/questions/58004237/critic-loss-for-rl-agent
Maybe you can test your learned policy on evaluation metrics such as profit?
