### ISSUE TITLE
max drawdown calculation

### ISSUE THREAD

**Issue by StevenHe2021** [TradeMaster-NTU/TradeMaster#65]
Is the max drawdown calculation correct in the evaluate function in TradeMaster\env\PM\portfolio_for_EIIE.py
It is calculated as 
mdd = max((max(df["total assets"]) - df["total assets"]) /max(df["total assets"]))
A very big increase in total assets may also be considered as max drawdown, e.g. An asset list like [1,5,4,3,2].

**Comment by qinmoelei** [comment]
Thanks for your feedback. We have updated the calculation of mdd.
