### ISSUE TITLE
Which example is about Commission Fee is not Enough: A Hierarchical Reinforced Framework for Portfolio Management (AAAI 2021)

### ISSUE THREAD

**Issue by JonathanHuangC** [TradeMaster-NTU/TradeMaster#81]
It is a great honor to read this paper published in AAAI in 2021,
Commission Fee is not Enough: A Hierarchical Reinforced Framework for Portfolio Management.

I would like to know which example I can refer to for the HRPM architecture of this paper.

Thanks.

**Comment by ai-gamer** [comment]
The code of HRPM is not available in the current code base. We rebuild the whole code structure and since HRPM is a hierarchical framework which is different from other methods. We need more time to reimplement it. Sorry for the inconvenience.

**Comment by JonathanHuangC** [comment]
Thank you for your reply.
Please notify me when it is updated if it is not troublesome.

**Comment by sunshuo01** [comment]
We will let you know when the implementation of the AAAI paper is available. Thanks for your interest on our work.
